import AppearanceEffect from "@/components/Providers/AppearanceEffect";
import ConvexClientProvider from "@/components/Providers/ConvexClientProvider";
import { ImageKitProviderWrapper } from "@/components/Providers/ImageKitProvider";
import LenisProvider from "@/components/Providers/LenisProvider";
import Footer from "@/components/UI/Footer/Footer";
import Nav from "@/components/UI/Header/Nav";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "sonner";
import "./globals.css";
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/convex.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <LenisProvider>
      <body className={`${inter.variable} antialiased`}>
        <NextTopLoader
          color="var(--primary)"
          easing="ease"
          shadow="0 0 10px 0 rgba(0, 0, 0, 0.1)"
          height={2.5}
          showSpinner={false}
        />
        <ConvexClientProvider>

          <ImageKitProviderWrapper>
            <Nav />

            <main className="relative flex-1 *:p-4">
              <AppearanceEffect>{children}</AppearanceEffect>
            </main>

            <Footer />
          </ImageKitProviderWrapper>
          <Toaster richColors position="bottom-right" />
          
        </ConvexClientProvider>
      </body>
      </LenisProvider>
    </html>
  );
}
