import ApperanceEffect from "@/components/Providers/ApperanceEffect";
import ConvexClientProvider from "@/components/Providers/ConvexClientProvider";
import LenisProvider from "@/components/Providers/LenisProvider";
import Nav from "@/components/UI/Header/Header";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/convex.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang="en">
        <body className={`${inter.variable} antialiased`}>
          <NextTopLoader
            color="var(--primary)"
            easing="ease"
            shadow="0 0 10px 0 rgba(0, 0, 0, 0.1)"
            height={2.5}
            showSpinner={false}
          />
          <ConvexClientProvider>
            <LenisProvider>
              <Nav>
                <ApperanceEffect>{children}</ApperanceEffect>
              </Nav>
            </LenisProvider>
          </ConvexClientProvider>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  );
}
